---
title: "arg_test"
---
<br>

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = ">"
)
```

```{r setup}
library(saferDev)
```
<br>

### Datasets
```{r}
f <- "unique"
f2 <- "plot"
argum <- c("x", "incomparables")
argum2 <- c("x", "y")
value <- list(x = list(1:10, c(1,1,2,8), NA), incomparable = c(TRUE, FALSE, NA))
value2 <- list(x = list(1:10, 12:13, NA, (1:10)^2),y = list(1:10, NA, NA))
error <- list(x = list(FALSE, FALSE, TRUE), incomparable = c(FALSE, FALSE, TRUE))
error2 <- list(x = list(FALSE, TRUE, TRUE, FALSE), y = list(FALSE, TRUE, TRUE))
```
<br>

### Datasets info
```{r}
f # character string indicating the name of the function tested 
argum # character vector of the arguments of fun
value # List in which each compartment containing values of the corresponding argument in arg
value2 # List in which each compartment containing values of the corresponding argument2 in arg
error # List indicating if an error is expected
```
<br>

### Simple examples
```{r}
arg_test(
    fun = f, 
    arg = argum, 
    val = value
)

arg_test(
    fun = f2, 
    arg = argum2, 
    val = value2
)

arg_test(
    fun = f, 
    arg = argum, 
    val = value,
    export = TRUE,
    res.path = getwd()
)

arg_test(
    fun = f2, 
    arg = argum2, 
    val = value2,
    expect.error = error2,
    plot.fun = TRUE,
    res.path = "."
)
```
<br>

### All the arguments
```{r}
arg_test(
    fun = f, 
    arg = argum, 
    val= value, 
    expect.error = error, 
    parall = FALSE, 
    thread.nb = NULL, 
    print.count = 10, 
    plot.fun = FALSE, 
    export = TRUE, 
    res.path = ".", 
    lib.path = NULL,
    safer_check = TRUE
) # check the function "mean" in the environment one step above the local environment
```