---
title: "is_python_package_here"
---
<br>

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = ">"
)
```

```{r setup}
library(saferDev)
```
<br>

### Datasets
```{r}
req.pkg <- "serpentine"
path <- "blablabla"
```
<br>

### Datasets info
```{r}
req.pkg # Character vector of package names to import
path # character vector specifying the absolute pathways of the directories, this lib_path will return an error
```
<br>

### Argument req.package
```{r, echo = TRUE, error = TRUE}
is_python_package_here(req.package = req.pkg) # check if the package serpentine is in the computer
```
<br>

### Argument lib_path
```{r, echo = TRUE, error = TRUE}
is_python_package_here(
    req.package = req.pkg,
    lib_path = path
) # check if the package is in the computer
```
<br>

### Argument safer_check
```{r, echo = TRUE, error = TRUE}
is_python_package_here(
    req.package = req.pkg,
    safer_check = TRUE
) # check if the package is in the computer, safer_check = TRUE, checkings are performed before main code running 
```
<br>

### All the arguments
```{r, echo = TRUE, error = TRUE}
is_python_package_here(
    req.package = "serpentine", 
    python.exec.path = ".", 
    python.lib_path = ".",
    lib_path = ".",
    safer_check =TRUE
) # check if the python package serpentine is present in the computer, returns an error if the package is not in the computer
```