---
title: "pkg_check"
---
<br>

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = ">"
)
```

```{r setup}
library(cuteDev)
```
<br>

### Datasets
```{r}
reqpkg <- "ggplot2"
grouppkg <- c("ggplot2", "usethis")
```
<br>

### Datasets info
```{r}
reqpkg # character vector of package names
grouppkg # character vector of package names
```
<br>

### Simple example
```{r}
pkg_check(req.package = reqpkg)
pkg_check(req.package = grouppkg)
```
<br>

### Argument load
```{r}
pkg_check(req.package = grouppkg, load = TRUE) # load the group of package in the environment 
```
<br>

### Argument lib.path
```{r}
pkg_check(req.package = grouppkg, lib.path = ".") # require the package contained in the absolute pathways of the directories
```
<br>

### All the arguments
```{r}
pkg_check(
    req.package = reqpkg, 
    load = TRUE,
    lib.path = "."
) # require the packages in the absolute pathways of the directories and load them in the environment
```