---
title: "report"
---
<br>

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = ">"
)
```

```{r setup}
library(saferDev)
```
<br>

### Datasets
```{r}
vec1 <- 1:6 # vector of integers
vec2 <- letters[1:9] # vector of characters
mat1 <- matrix(vec1, nrow = 2, ncol = 3, byrow = TRUE) # matrix of integer having 2 rows and 3 columns
dimnames(mat1) <- list(c("Row 1","Row 2"), c("C1", "C2", "C3"))
t1 <- table(mat1) # 
vec3 <- as.vector(t1)
names(vec3) <- letters[1:9]
t2 <- table(vec2, vec2)
```
<br>

### Datasets info
```{r}
vec1 # vector of integers
vec2 # vector of characters
vec3 # vector of integers with names
mat1 # matrix of integers with spaces in row names
t1 # 1D table with row names (above the values)
t2 # 2D table with row names

```
<br>

### Simple examples
```{r}
# print the object into the output file in the path (without row names by default)
report(data = vec1, path = ".")
report(data = vec2, path = ".")
report(data = vec3, path = ".")
report(data = mat1, path = ".")
report(data = t1, path = ".")
report(data = t2, path = ".")
```
<br>

### Argument output
```{r, echo = TRUE, error = TRUE}
report(data = vec1, output = "test.txt", path = ".") # print the vector vec1 into the output file named "test.txt" in the path
```
<br>

### Argument overwrite
```{r, echo = TRUE, error = TRUE}
report(data = vec2, overwrite = TRUE, path = ".") # if the file exists, the output file content will be erased before printing
```
<br>

### Argument rownames.kept
```{r, echo = TRUE, error = TRUE}
# keep the row names when printing the object in the file
report(
  data = mat1, 
  rownames.kept = TRUE, 
  path = "."
) 

report(
  data = t1, 
  rownames.kept = TRUE, 
  path = "."
) 

report(
  data = t2, 
  rownames.kept = TRUE, 
  path = "."
) 

# Names in vectors are not row names, as in 1D table (names not removed with rownames.kept = FALSE)
report(
  data = vec3, 
  rownames.kept = FALSE, 
  path = "."
)

```
<br>

### Argument vector.cat
```{r, echo = TRUE, error = TRUE}
report(
  data = mat2, 
  vector.cat = TRUE, 
  path = "."
) # print a vector of length > 1 using cat() instead of capture.output()
```
<br>

### Argument noquote
```{r, echo = TRUE, error = TRUE}
report(
  data = mat2, 
  noquote = FALSE, 
  path = "."
) # quote are present for the characters.
```
<br>

### Argument sep
```{r, echo = TRUE, error = TRUE}
report(
  data = vec1, 
  sep = 4, 
  path = "."
) # 4 lines after printed data
```
<br>

### All the arguments
```{r, echo = TRUE, error = TRUE}
report(
    data = mat2, 
    output = "test.txt", 
    path = ".", 
    overwrite = TRUE, 
    rownames.kept = TRUE, 
    vector.cat = TRUE, 
    noquote = FALSE, 
    sep = 4,
    safer_check = TRUE
)
# matrix mat2 will be print in the file "text.txt" in the path, with quote and row names being kept, and 4 lines after printing data
```

