---
title: "devCute"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{devCute}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r include = FALSE}
library(devCute)
```
 

### Examples of fun_check

```{r, echo = TRUE, error = TRUE}
### Datasets
vec1 <- -1:3 # vector of integers
vec2 <- 1:3 / 3 # vector of proportions
vec3 <- c(1, 2, 3) # vector of integers but stored as "double"
vec4 <- "pearson" # vector of characters
vec5 <- c("a", "b","a", "b") # vector of characters
mat1 <- matrix(vec1) # matrix of integers
mat2 <- matrix(c(1:3 / 3, NA)) # matrix of proportions with NA


### Datasets info
# vec1 # vector of integers
# vec2 # vector of proportions
# vec3 # vector of integers but stored as "double"
# vec4 # vector of characters
# vec5 # vector of characters
# mat1 # matrix of integers
# mat2 # matrix of proportions with NA


### Simple examples
# Check that vec1 is of class integer (means that it is also a vector) -> ok
fun_check(data = vec1, class = "integer")
# Check that vec1 is a numeric vector -> error because vec1 is a vector of integers
fun_check(data = vec1, class = "numeric")
# Check that vec1 is an integer vector of length 3 without negative values and without NA -> error because of length 5 and negative values inside vec1
fun_check(data = vec1, class = "vector", typeof = "integer", length = 3, neg.values = FALSE, na.contain = FALSE)
# No result displayed because the output list is assigned into res (see below the print argument)
res <- fun_check(data = vec1, class = "integer")

# with data = NULL, the function systematically report a checking problem
fun_check(data = NULL, class = "integer")

### Argument class, typeof, mode and length are the same as the corresponding R function, except class which 1) has also "vector" and 2) remains "matrix" for matrices and not "matrix" "array"
# Example
fun_check(data = vec1, 
    class = "vector", 
    typeof = "integer", 
    mode = "numeric", 
    length = 5, 
)
# Warning: the function does not check for inconsistencies between arguments. It just checks if everything is ok between arguments values and data
fun_check(data = vec1, 
    typeof = "integer", 
    mode = "character", # the mode "character" exists but is inconsistant with typeof "integer". However, this aspect is not signaled by the function
)

# Error message due to wrong value in the class and length arguments
fun_check(data = vec1, 
    mode = "integer", # the mode "integer" does not exist in the mode() function of R
)

### Argument prop
fun_check(data = mat2, 
    prop = TRUE # Check for values between 0 and 1 only
)

### Argument double.as.integer.allowed
fun_check(data = vec3, typeof = "integer",
    double.as.integer.allowed = TRUE # with TRUE, integers stored as double are accepted
)

### Argument options
fun_check(data = vec4, 
    options = c("pearson", "spearman", "kendall")
)

### Argument all.options.in.data
# No error
fun_check(data = vec5,
    options = c("a", "b"), 
    all.options.in.data = TRUE
)
# No error
fun_check(data = vec5,
    options = c("a", "b", "c"), 
    all.options.in.data = FALSE
)
# Error
fun_check(data = vec5,
    options = c("a", "b", "c"), 
    all.options.in.data = TRUE
)

### Argument na.contain
fun_check(data = mat2, class = "matrix", prop = TRUE,
    na.contain = FALSE # with TRUE, integers stored as double are accepted
)

### Argument neg.values
# Warning: only considered if set to FALSE, to check for non negative values when class is set to "vector", "numeric", "matrix", "array", "data.frame", "table", or typeof is set to "double", "integer", or mode is set to "numeric"
fun_check(data = mat1, class = "matrix",
    neg.values = FALSE # with TRUE, integers stored as double are accepted
)

### Argument inf.values
# Warning: only considered if set to FALSE, to check for non infinite values when class is set to "vector", "numeric", "matrix", "array", "data.frame", "table", or typeof is set to "double", "integer", or mode is set to "numeric"
fun_check(data = mat1, class = "matrix",
    inf.values = FALSE
)

### Argument print
# No error message printed because print is FALSE
res <- fun_check(data = mat1, class = "data.frame",
    print = FALSE
)
# Error message printed
res <- fun_check(data = mat1, class = "data.frame",
    print = TRUE
)
# Even if print is TRUE, no error message printed because no error
res <- fun_check(data = mat1, class = "matrix",
    print = TRUE
)


### Arguments data.name and fun.name
# Example
tempo <- fun_check(data = vec1, class = "integer", 
    data.name = "OBSERVATION_1", 
    fun.name = "FUNCTION_1"
)
tempo$text
# In fact, these two arguments are interesting when check() is used inside functions
fun1 <- function(arg1){
    tempo <- fun_check(data = arg1, class = "integer", 
        data.name = NULL, # if NULL, the name displayed is arg1
        fun.name = NULL # if NULL, no name displayed
    )
    if(tempo$problem == TRUE){
        cat(paste0("\n\n================\n\n", tempo$text, "\n\n================\n\n"))
    }
}
fun1(arg1 = vec4) # error message because arg1 requires a vector of integers



### All the arguments
# See the examples of fun_info() to test different classes of objects
fun_check(
    data = vec1, 
    class = "integer", 
    typeof = NULL, 
    mode = NULL, 
    length = NULL, 
    prop = FALSE, 
    double.as.integer.allowed = FALSE, 
    options = NULL, 
    all.options.in.data = FALSE, 
    na.contain = FALSE, 
    neg.values = TRUE, 
    inf.values = TRUE, 
    print = FALSE, 
    data.name = NULL, 
    fun.name = NULL
)
```

### Examples of fun_pack

```{r}
### Datasets
reqpkg <- "ggplot2"
grouppkg <- c("ggplot2", "usethis")

### Datasets info
# reqpkg # character vector of package names
# grouppkg # character vector of package names

### Simple example
fun_pack(req.package = reqpkg)
fun_pack(req.package = grouppkg)

### Argument load
fun_pack(req.package = grouppkg, load = TRUE) # load the group of package in the environment 

### Argument lib.path
fun_pack(req.package = grouppkg, lib.path = "C:/Users/yhan/AppData/Local/R/win-library/4.3") # require the package contained in the absolute pathways of the directories

### All the arguments
fun_pack(
    req.package = reqpkg, 
    load = TRUE,
    lib.path = "C:/Users/yhan/AppData/Local/R/win-library/4.3"
) # require the packages in the absolute pathways of the directories and load them in the environment
```


### Examples of fun_get_message
```{r}
### Datasets
char1 <- "wilcox.test(c(1,1,3), c(1, 2, 4), paired = TRUE)" # single character string
char2 <- "message('ahah')" # single character string

### Datasets info
# char1 # single character string
# char2 # single character string

### Simple example
fun_get_message(data = char1)
fun_get_message(data = char2)

### Argument kind
fun_get_message(data = char1, kind = "warning") # to get warning messages of the wilcox test

### Argument header
fun_get_message(data = char1, header = FALSE) # to get error messages (by default) without header

### Argument print.no
fun_get_message(data = char1, print.no = TRUE) # print a message saying that no message reported

### Argument text
fun_get_message(data = char2, print.no = TRUE, text = "IN A") # print a message even if the argument print.no is TRUE

### Argument kind, header, print.no, text
fun_get_message(data = char1, kind = "warning", header = FALSE, print.no = TRUE, text = "IN A") # print the warning message in text

### All the arguments
fun_get_message(
    data = char1, 
    kind = "warning", 
    header = FALSE,
    print.no = TRUE, 
    text = "IN A",
    env = NULL
) # print the warning message in text in the environment R_GlobalEnv
```


### Examples of fun_secu
```{r}
### Argument pos
fun_secu(pos = 2) # check the objects in the environment 2 steps above the fun_secu() local environment

### Argument name
fun_secu(name = "mean") # check the function mean() in the environment 1 step above the fun_secu() local environment (by default)

### All the arguments
fun_secu(
    pos = 2, 
    name = "mean"
) # check the function mean in the environment 2 steps above the fun_secu() local environment
```

### Examples of fun_report

```{r}
### Datasets
vec1 <- 1:6 # vector of integers
vec2 <- c("(","a",")","(","b",")","(","c",")") # vector of characters
mat1 <- matrix(vec1, nrow = 2, ncol = 3, byrow = TRUE) # matrix of integer having 2 rows and 3 columns
rownames(mat1) <- c("Row 1","Row 2")
mat2 <- matrix(vec2, nrow = 3, ncol = 3, byrow = TRUE) # matrix of integer having 3 rows and 3 columns
rownames(mat2) <- c("R1","R2","R3")


### Datasets info
# vec1 # vector of integers
# vec2 # vector of characters
# mat1 # matrix of integers with the row names
# mat2 # matrix of characters with the row names

### Simple examples
fun_report(data = vec1, path = "C:/Users/yhan/Desktop") # print the vector vec1 into the output file in the path "C:\Users\yhan\Desktop"
fun_report(data = vec2, path = "C:/Users/yhan/Desktop") # print the vector vec2 into the output file in the path "C:\Users\yhan\Desktop"
fun_report(data = mat1, path = "C:/Users/yhan/Desktop") # print the matrix mat1 into the output file in the path "C:\Users\yhan\Desktop"
fun_report(data = mat2, path = "C:/Users/yhan/Desktop") # print the matrix mat2 into the output file in the path "C:\Users\yhan\Desktop"

### Argument output
fun_report(data = vec1, output = "test.txt", path = "C:/Users/yhan/Desktop") # print the vector vec1 into the output file named "test.txt" in the path "C:\Users\yhan\Desktop"

### Argument overwrite
fun_report(data = vec2, overwrite = TRUE, path = "C:/Users/yhan/Desktop") # if the file exists, the output file content will be erased before printing

### Argument rownames.kept
fun_report(data = mat1, rownames.kept = TRUE, path = "C:/Users/yhan/Desktop") # keep the row names when print the matrix mat1 in the file

### Argument vector.cat
fun_report(data = mat2, vector.cat = TRUE, path = "C:/Users/yhan/Desktop") # print a vector of length > 1 using cat() instead of capture.output()

### Argument noquote
fun_report(data = mat2, noquote = FALSE, path = "C:/Users/yhan/Desktop") # quote are present for the characters.

### Argument sep
fun_report(data = vec1, sep = 4, path = "C:/Users/yhan/Desktop") # 4 lines after printed data

### All the arguments
fun_report(
    data = mat2, 
    output = "test.txt", 
    path = "C:/Users/yhan/Desktop", 
    overwrite = TRUE, 
    rownames.kept = TRUE, 
    vector.cat = TRUE, 
    noquote = FALSE, 
    sep = 4
) 
# matrix mat2 will be print in the file "text.txt" in the path "C:\Users\yhan\Desktop",with quote and row names being kept, and 4 lines after printing data
```

