---
title: "all_args_here"
---
<br>

```{r, include = FALSE}
knitr::opts_chunk$set(
    error = TRUE, 
    collapse = TRUE,
    comment = ">"
)
```

```{r setup}
library(saferDev)
```
<br>

### Datasets
```{r}
source("https://raw.githubusercontent.com/safer-r/saferDev/main/dev/other/test2.R")
source("https://raw.githubusercontent.com/safer-r/.github/refs/heads/main/profile/backbone.R")
FUN1 <- function(x, y){
    code_for_col <- base::as.vector(x = base::unlist(x = base::mapply(FUN = function(x, y){base::rep(x = y, base::length(x = x))}, x = x, y = y, MoreArgs = NULL, SIMPLIFY = TRUE, USE.NAMES = TRUE), recursive = TRUE, use.names = TRUE), mode = "any")
    code_for_col2 <- base::as.vector(x = base::unlist(x = base::mapply(FUN = function(x, y){base::rep(x = y, base::length(x = x))}, x = x, y = y)))
    middle_bracket <- base::do.call(what = base::c, args = code_for_col)
    middle_bracket2 <- base::do.call(what = base::c, args = code_for_col, quote = FALSE, envir = base::parent.frame())
}
FUN2 <- function(x, y){
    middle_bracket2 <- base::do.call(what = base::c, args = code_for_col, quote = FALSE, envir = base::parent.frame())
}
```
<br>



### Simple examples
```{r}
# Examples that return an error
# all_args_here(mean)
# all_args_here(test2)
all_args_here(
    x = FUN2 # R function
)
```
<br>

### Argument export (associated with argument path_out, df_name and overwrite)
```{r}
all_args_here(
    x = FUN2, # R function
    export = TRUE, # export the data frame into a .tsv file?
    path_out = ".", # pathway of the folder where to export the data frame
    df_name = "res.tsv", # name of the exported data frame file
    overwrite = TRUE # Overwrite potential df_name file already existing in path_out?
)
```
<br>


### All the arguments
```{r}
all_args_here(
    x = FUN1, # R function
    export = FALSE, # export the data frame into a .tsv file?
    path_out = ".", # pathway of the folder where to export the data frame.
    df_name = "res.tsv", # name of the exported data frame file
    overwrite = FALSE, # Overwrite potential df_name file already existing in path_out?
    safer_check = TRUE, # perform some "safer" checks? Warning : always set this argument to FALSE if all_args_here() is used inside another safer function.
    lib_path = NULL, # absolute pathways of the directories containing the required packages if not in the default directories.
    error_text = "" # add information in error messages returned by the function.
)

```
<br>