---
title: "colons_check"
---
<br>

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = ">"
)
```

```{r setup}
library(saferDev)
```
<br>

### Datasets

```{r}
fun1 <- function(){
    base::sum(1, 3)
  }

fun2 <- function(){
    sum(1, 3)
  }
```
<br>

### Datasets info

```{r}
fun1
fun2
```
<br>

### Argument x
```{r, echo = TRUE, error = TRUE}
colons_check(x = fun1) # a function name, written without quotes and brackets
colons_check(x = fun2) # a function name, written without quotes and brackets
```
<br>

### Argument safer_chek 
```{r, echo = TRUE, error = TRUE}
colons_check(
    x = fun1, 
    afer_check = FALSE
) # Single logical value. Perform some "safer" checks (see https://github.com/safer-r) ?
```
<br>

### All the arguments
```{r, echo = TRUE, error = TRUE}
colons_check(
    x = fun1, # a function name, written without quotes and brackets
    safer_check = TRUE, # perform some "safer" checks? Warning : always set this argument to FALSE if all_args_here() is used inside another safer function.
    lib_path = NULL, # absolute pathways of the directories containing the required packages if not in the default directories.
    error_text = "" # add information in error messages returned by the function.
)
```
<br>

### Sophisticated example
```{r, echo = TRUE, error = TRUE}
source("https://raw.githubusercontent.com/safer-r/saferDev/main/dev/other/test.R")
colons_check(
    x = test, # a function name, written without quotes and brackets
    safer_check = TRUE # Single logical value. Perform some "safer" checks (see https://github.com/safer-r) ?
)
```
<br>
