---
title: "is_function_here"
---
<br>

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = ">"
)
```

```{r setup}
library(saferDev)
```
<br>

### Datasets
```{r}
f <- "ggplot2::geom_point"
path <- "blablabla"
```
<br>

### Datasets info
```{r}
f # Character vector of function name
path # character vector specifying the absolute pathways of the directories, this lib_path will return an error
```
<br>

### Argument fun
```{r, echo = TRUE, error = TRUE}
is_function_here(fun = f) # check if the package serpentine is in the computer
```
<br>

### Argument safer_check
```{r, echo = TRUE, error = TRUE}
is_function_here(
    fun = f,
    safer_check = TRUE
) # check if the package is in the computer, safer_check = TRUE, checkings are performed before main code running 
```
<br>

### Argument lib_path and error_text
```{r}
is_function_here(
    fun = f,
    lib_path = ".", # absolute pathways of the directories containing the required packages if not in the default directories.
    error_text = "TEXT ADDED" # add information in error messages returned by the function.
)
```
<br>

### All the arguments
```{r, echo = TRUE, error = TRUE}
is_function_here(
    fun = f,
    safer_check = TRUE, # perform some "safer" checks? Warning : always set this argument to FALSE if all_args_here() is used inside another safer function.
    lib_path = NULL, # absolute pathways of the directories containing the required packages if not in the default directories.
    error_text = "" # add information in error messages returned by the function.
) # check if the function is present in the package, returns an error because the path doesn't exist
```
<br>

