---
title: "all_args_here(): more examples"
---
<br>

```{r, include = FALSE}
knitr::opts_chunk$set(
    error = TRUE, 
    collapse = FALSE,
    comment = "##"
)
```

```{r setup}
library(saferDev)
```
<br>

### Dataset
```{r}
source("https://raw.githubusercontent.com/safer-r/saferDev/main/dev/other/test2.R") # function.
source("https://raw.githubusercontent.com/safer-r/.github/refs/heads/main/profile/backbone.R") # function.
FUN1 <- function(x, y){ # vector of integers
    code_for_col <- base::as.vector(x = base::unlist(x = base::mapply(FUN = function(x, y){base::rep(x = y, base::length(x = x))}, x = x, y = y, MoreArgs = NULL, SIMPLIFY = TRUE, USE.NAMES = TRUE), recursive = TRUE, use.names = TRUE), mode = "any")
    code_for_col2 <- base::as.vector(x = base::unlist(x = base::mapply(FUN = function(x, y){base::rep(x = y, base::length(x = x))}, x = x, y = y)))
    middle_bracket <- base::do.call(what = base::c, args = code_for_col)
    middle_bracket2 <- base::do.call(what = base::c, args = code_for_col, quote = FALSE, envir = base::parent.frame())
}
FUN2 <- function(x, y){ # function.
    middle_bracket2 <- base::do.call(what = base::c, args = code_for_col, quote = FALSE, envir = base::parent.frame())
}
```
<br>



### Simple examples
```{r}
# Example that return an error.
all_args_here(mean)
# Example that return an error.
all_args_here(test2)
all_args_here(
    x = FUN2
)
```
<br>

### Arguments <code>export</code>, <code>out_path</code>, <code>df_name</code> and <code>overwrite</code>
```{r}
# Print the results into the res.tsv file written in the "." path, and overwrite if res.tsv already exists in ".".
all_args_here(
    x = FUN2, 
    export = TRUE, 
    out_path = ".", 
    df_name = "res.tsv", 
    overwrite = TRU
)
```
<br>

### Argument <code>safer_check</code>
```{r, echo = TRUE, error = TRUE}
# Safer checkings are performed before main code running 
all_args_here(
    x = FUN2, 
    safer_check = TRUE
)
```
<br>

### Argument <code>lib_path</code>
```{r}
# Error returned because the R required packages are not in the "." path.
all_args_here(
    x = FUN2,  
    lib_path = "."
)
```
<br>

### Argument <code>error_text</code>
```{r}
# Add a text in error messages returned by all_args_here().
all_args_here(
    x = FUN2, 
    lib_path = ".", 
    error_text = " === TEXT ADDED ==="
)
```
<br>

### All the arguments
```{r}
all_args_here(
    x = FUN1, # R function.
    export = FALSE, # export the data frame into a .tsv file?
    out_path = ".", # pathway of the folder where to export the data frame.
    df_name = "res.tsv", # name of the exported data frame file.
    overwrite = FALSE, # Overwrite potential df_name file already existing in out_path?
    safer_check = TRUE, # Single logical value. Perform some "safer" checks (see https://github.com/safer-r)?
    lib_path = NULL, # absolute pathways of the directories containing the required packages if not in the default directories.
    error_text = "" # add information in error messages returned by the function.
)

```
<br>