---
title: "get_message(): more examples"
---
<br>

```{r, include = FALSE}
knitr::opts_chunk$set(
    error = TRUE, 
    collapse = FALSE,
    comment = "##"
)
```

```{r setup}
library(saferDev)
```
<br>

#### get_message() 

#### return error/warning/other messages of an expression (that can be exported)
<br>

### Dataset

```{r}
char1 <- "wilcox.test(c(1,1,3), c(1, 2, 4), paired = TRUE)" # single character string of a command to evaluate
char2 <- "message('ahah')" # single character string single character string of a command to evaluate
```
<br>

### Dataset info
```{r}
char1 # single character string
char2 # single character string
```
<br>

### Simple example
```{r}
get_message(data = char1) # single character string of a command to evaluate
get_message(data = char2) # single character string of a command to evaluate
```
<br>

### Argument <code>kind</code>
```{r}
get_message(data = char1, kind = "warning") # to get the first warning message of the wilcox test
```
<br>

### Argument <code>header</code>
```{r}
get_message(data = char1, header = FALSE) # to get error messages (by default) without header
```
<br>

### Argument <code>print_no</code>
```{r}
get_message(data = char1, print_no = TRUE) # print a message when no error reported
```
<br>

### Argument <code>text</code>
```{r}
get_message(
    data = char2, # single character string of a command to evaluate
    print_no = TRUE, # print a message when no error reported
    text = "IN A" # single character string added to the output message (even if nothing reported)
) 
```
<br>

### Argument <code>kind</code>, <code>header</code>, <code>print_no</code> and <code>text</code>
```{r}
get_message(
    data = char1, 
    kind = "warning", # to get the first warning message
    header = FALSE, # to get error messages (by default) without header
    print_no = TRUE, # print a message when no error reported
    text = "IN A" # single character string added to the output message (even if nothing reported)
) # print the warning message in text
```
<br>

### Argument <code>env</code>
```{r}
get_message(data = char1, env = 2) # object corresponding to an existing environment. Then the \code{data} argument value is evaluated only in the indicated environment. Write \code{NULL} if not required (R scope is used). Example \code{env = .GlobalEnv}.
```
<br>

### Argument <code>safer_check</code>
```{r}
get_message(data = char2, safer_check = TRUE) # with TRUE, checkings are performed before main code running
```
<br>

### Argument <code>lib_path</code> and <code>error_text</code>
```{r}
get_message(
    lib_path = ".", # absolute pathways of the directories containing the required packages if not in the default directories.
    error_text = "TEXT ADDED" # add information in error messages returned by the function.
)
```


### All the arguments
```{r}
get_message(
    data = char1, 
    kind = "warning", # to get the first warning message
    header = FALSE, # to get error messages (by default) without header
    print_no = TRUE, # print a message when no error reported
    text = "IN A", # single character string added to the output message (even if nothing reported)
    env = NULL,
    safer_check = TRUE, # Single logical value. Perform some "safer" checks (see https://github.com/safer-r)?
    lib_path = NULL, # absolute pathways of the directories containing the required packages if not in the default directories.
    error_text = "" # add information in error messages returned by the function.
) # print the warning message in text in the environment R_GlobalEnv
```


