---
title: "is_package_here(): more examples"
---
<br>

```{r, include = FALSE}
knitr::opts_chunk$set(
    error = TRUE, 
    collapse = FALSE,
    comment = "##"
)
```

```{r setup}
library(saferDev)
```
<br>

### Datasets
```{r}
req.pkg <- "ggplot2"
```
<br>

### Datasets info
```{r}
req.pkg # package name between quotes.
```
<br>

### Argument <code>req_package</code>
```{r, echo = TRUE, error = TRUE}
# check if the ggplot2 package is in the default library folder.
is_package_here(req_package = req.pkg) 
```
<br>

### Argument <code>safer_check</code>
```{r, echo = TRUE, error = TRUE}
# Safer checkings are performed before main code running.
is_package_here(req_package = req.pkg, safer_check = TRUE)
```
<br>

### Argument <code>lib_path</code>
```{r}
# The ggplot2 package is in one of the paths c(".", .libPaths()).
is_package_here(req_package = req.pkg, lib_path = ".")

# The ggplot2 package is in the default path (.libPaths()).
is_package_here(req_package = req.pkg, lib_path = NULL)

# The "NOTGOOD" path does not exists.
is_package_here(req_package = req.pkg, lib_path = "NOTGOOD")
```
<br>

### Argument <code>error_text</code>
```{r}
# Add a text in error messages returned by is_package_here().
is_package_here(
    req_package = req.pkg, 
    lib_path = "NOTGOOD", 
    error_text = " === TEXT ADDED ==="
)
```
<br>

### All the arguments
```{r, echo = TRUE, error = TRUE}
is_package_here(
    req_package = req.pkg, # package name string (between quotes).
    safer_check = TRUE, # perform some "safer" checks (see https://github.com/safer-r)?
    lib_path = NULL, # where the required packages are if not in the default directories.
    error_text = "" # add information in error messages returned by the function.
) 
```
```